name: tbd-env
channels:
 - conda-forge
 - pytorch
dependencies:
  - python=3.6
  - numpy=1.13.3
  - matplotlib=2.0
  - scipy=0.19.1
  - torchvision
  - typing
  - scikit-image
  - six
  - pillow
  - configobj
  - argparse=1.4
  - pyvox
  - pandas
  - torchmetrics